# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cAiTRPHitM5QG_6ZjySyC657ODFz2fZo
"""

!pip install streamlit

# Lista de frases
frases = [
"Eres mi bien Giffen: cuanto más te tengo, más te necesito.",
"Te pienso más que a una función objetivo al hacer Langrangianos.",
"Tu amor es el único bien que no tiene sustitutos perfectos.",
"Sin ti, mi función de producción no tiene rendimientos crecientes.",
"Eres la constante que estabiliza todas mis ecuaciones.",
"Mi amor por ti tiene varianza cero: es constante e infinito.",
"Eres la raíz de todas mis funciones con sentido.",
"Mi afecto por ti es más fuerte que una correlación perfecta.",
"En mi sistema de ecuaciones, tú eres la única solución posible.",
"Juntos somos un sistema lineal compatible determinado: hechos el uno para el otro.",
"Contigo mi utilidad se maximiza bajo cualquier restricción presupuestaria.",
"Eres mi función cóncava: solo tienes un máximo, y soy yo contigo.",
"Amarte no es racional, es completamente eficiente.",
"Nuestro amor tiene elasticidad unitaria: crece justo a la par que mis ganas de abrazarte.",
"Eres como una externalidad positiva en mi día a día.",
"En el espacio vectorial de mi vida, tú eres los vectores de mi span (la base JAJKSAJA).",
"Contigo, todos mis vectores apuntan al mismo sentido: el amor.",
"Mis sentimientos por ti tienen un intervalo de confianza del 99.99%.",
"Te pienso más que a una hipótesis nula en el final de esta 1.",
"Eres el límite al que tiendo cada vez que me alejo.",
"Tu cariño es más reconfortante que una matriz 2x2 en mate.",
"El amor que siento por ti no tiene puntos críticos: siempre crece.",
"Tu ternura reduce mi curva de indiferencia ante todo lo demás.",
"Estás tan presente en mí como λ en toda la matemática.",
"Podré tener mil datos, pero tú eres mi muestra representativa de amor.",
"Cuando me hablas, se me despejan todas las incógnitas.",
"Respira, mi amor. No tienes que poder con todo hoy. Solo con lo que puedas, y eso ya está bien.",
"Estoy orgulloso de ti, incluso cuando no lo estás tú mismo. Porque yo sí te veo.",
"El mundo puede ser frío, pero tú tienes mi amor calentito esperándote siempre.",
"No estás solo. Nunca lo estás. Yo estoy aquí, contigo, y para ti.",
"Aunque hoy duela, esto también pasará. Mientras tanto, te abrazo desde mi corazón.",
"No olvides que vales más de lo que hoy te deja ver tu mente cansada.",
"Puedes llorar si lo necesitas. Sentir no te hace débil, te hace humano.",
"Descansa un ratito. El mundo puede esperar. Tú eres lo importante ahora.",
"Hoy puedes ser suave contigo. No hace falta exigirte tanto, amor.",
"No eres una carga, eres una persona pasando por mucho. Y aún así, sigues.",
"Me importas más de lo que las palabras alcanzan a decir. Si pudiera, te abrazaría todo el día. —Dieguito 💚",
"Te amo incluso en tus silencios. Especialmente ahí. —Dieguito 💚",
"No tienes que explicarme nada, solo déjame acompañarte como tú me acompañas a mí. —Dieguito 💚",
"Tu tristeza no me espanta, amor. Yo estoy contigo en cada emoción. —Dieguito 💚",
"Cuando sientas que nadie te entiende, recuerda que yo sí. Siempre. —Dieguito 💚",
"Hoy puedes no estar bien. No pasa nada. No estás solo.",
"Puedes caer, pero también vas a levantarte. Y cuando no puedas solo, yo estaré ahí.",
"No eres tus pensamientos tristes. Eres mucho más.",
"Abre este mensajito y deja que te abrace con palabras.",
"Si supieras lo fuerte que eres por seguir incluso con dolor… te admirarías tanto como yo te admiro.",
"No tienes que dar tu 100% hoy. Con dar lo que puedas, ya es suficiente.",
"Cada pasito que das, por más pequeño, cuenta. No te minimices.",
"Lo estás haciendo bien, incluso cuando no se siente así.",
"Permitido llorar… pero también reírte porque tienes la app más amorosa del mundo.",
"Tu tristeza no me aleja, me dan más ganas de cuidarte. —Dieguito 💚",
"No sé qué harás hoy, pero yo ya decidí amarte igual que siempre. —Dieguito 💚",
"Lucho, tú eres mi lugar seguro. Y quiero serlo para ti también. —Dieguito 💚",
"¿Ya te dije que eres mi persona favorita? Porque lo eres. Incluso con los ojos llorosos. —Dieguito 💚",
"No importa lo que pase hoy, aquí estoy. Te amo en calma, y también en caos. —Dieguito 💚",
"No tienes que controlar todo. A veces solo respirar y dejar que pase es suficiente.",
"Las emociones vienen y van. Lo importante es que tú permanezcas contigo.",
"Ser sensible no es un defecto. Es un superpoder malentendido.",
"Tu valor no cambia por cómo te sientas. Sigues siendo tú, y eso ya es mucho.",
"Está bien no ser productivo todo el tiempo. También mereces descanso.",
"Si pudiera, te envolvería como un burrito y no te soltaría hasta que sonrías.",
"Imagínate esto: tú y yo abrazados, viendo tiktoks bonitos. No soluciona todo, pero suena bien, ¿no?",
"Te extraño cada vez que tu ánimo se apaga. Quisiera entrar ahí y volver a encenderte poquito a poquito.",
"A veces solo necesitas un abrazo. Y este mensaje quiere serlo."
]

import streamlit as st
import random

st.title("💚 Mensajitos para Luis")
st.write("Toca el botón si estás bajoneado y quieres algo bonito 🥺")

if st.button("Dame un mensajito 💌"):
    st.success(random.choice(frases))